linters:
  enable:
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - errcheck
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - gofmt
  - goimports
  - golint
  - gomnd
  - gosec
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - lll
  - maligned
  - misspell
  - nakedret
  - prealloc
  - scopelint
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
  - wsl
